### ISSUE TITLE
Sorry:Error: No text selected

### ISSUE THREAD

**Issue by jmouchnino** [cran/ViewPipeSteps#1]
When I click outside the script after selecting the code hat I want to print, there's an error message :
`Sorry:Error: No text selected`

I'm aware that it's because I clicked outside the script (in the console)  but is this something that might be fixed ?

![view_pipe](https://user-images.githubusercontent.com/103758616/182520972-f035f939-de09-493e-807c-001163bc4bee.gif)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by jmouchnino** [comment]
Indeed, I noticed that after I posted, but I don't see how to delete the issue on GitHub
